name: Llama-Games
api-version: 1.17
main: io.github.lama06.llamagames.LlamaGamesPlugin
version: 1.0.0

commands:
  lamagames:
    description: The main command of the LlamaGames plugin
  lamasays:
    description: Used to setup LlamaSays games
