name: Llama-Games
author: Lama06
api-version: 1.18
main: io.github.lama06.llamagames.LlamaGamesPlugin
version: 1.0.0
softdepend:
  - Multiverse-Core

commands:
  llamagames:
    description: The main command of the LlamaGames plugin
  llamasays:
    description: Used to setup LlamaSays games
  blockparty:
    description: Used to setup BlockParty games
  zombies:
    description: Used to setup Zombies games
