name: Llama-Plugin
website: github.com/Lama06/Llama-Games
author: Lama06
api-version: 1.18
main: io.github.lama06.llamaplugin.LlamaPlugin
version: 1.0.0
softdepend:
  - Multiverse-Core

commands:
  llamaplugin:
    description: The main command of the LlamaPlugin
  llamagames:
    description: The main command of the LlamaGames module
  llamasays:
    description: Used to setup LlamaSays games
  blockparty:
    description: Used to setup BlockParty games
  zombies:
    description: Used to setup Zombies games
  thefloorislava:
    description: Used to setup TheFloorIsLava games
