name: Llama-Games
api-version: 1.17
main: io.github.lama06.llamagames.LlamaGamesPlugin
version: 1.0.0

commands:
  llamagames:
    description: The main command of the LlamaGames plugin
  llamasays:
    description: Used to setup LlamaSays games
  blockparty:
    description: Used to setup BlockParty games
